/**
 * Browser-Use Python Code Generator
 * 
 * Generates browser-use compatible Python code from recorded actions.
 * 
 * @see https://github.com/browser-use/browser-use
 */
import { RecordedAction, ScriptGeneratorOptions } from '../types'

export class BrowserUseGenerator {
  private options: ScriptGeneratorOptions

  constructor(options: ScriptGeneratorOptions = {}) {
    this.options = {
      includeComments: true,
      useAsyncAwait: true,
      addDelays: true,
      ...options,
    }
  }

  generate(
    profileId: string,
    prompt: string,
    actions: RecordedAction[]
  ): string {
    const timestamp = new Date().toISOString()
    const extractedFields = new Set<string>()

    actions.forEach((a) => {
      if (a.type === 'extract' && a.value) {
        extractedFields.add(a.value)
      }
    })

    return `"""
AUTO-GENERATED by browser-use-codegen

Task: "${this.escapePythonString(prompt)}"
Generated: ${timestamp}
Profile: ${profileId}
Actions: ${actions.length}

Requires:
    pip install browser-use

Usage:
    python script.py
"""

import asyncio
from browser_use import Agent, Browser, BrowserConfig
from langchain_openai import ChatOpenAI


async def run_task():
    """
    ${this.escapePythonString(prompt)}
    """
    
    # Configure browser
    browser = Browser(config=BrowserConfig(
        headless=False,  # Set to True for production
        # Add your browser config here
    ))
    
    # Initialize LLM (configure your API key)
    llm = ChatOpenAI(model="gpt-4o", temperature=0.0)
    
    # Create agent with high-level task
    agent = Agent(
        task="""${this.escapePythonString(prompt)}""",
        llm=llm,
        browser=browser,
        use_vision=True,  # Enable visual understanding
    )
    
    # Run the agent
    result = await agent.run()
    
    print("\\n✅ Task completed!")
    print(f"Result: {result}")
    
    await browser.close()
    
    return result


# Alternative: Direct step-by-step implementation
async def run_steps():
    """
    Step-by-step implementation based on recorded actions.
    Use this for more control over the automation.
    """
    from browser_use import Controller
    
    controller = Controller()
    browser = Browser(config=BrowserConfig(headless=False))
    
    try:
${this.generateActionsCode(actions)}
        
        return {"success": True}
        
    finally:
        await browser.close()


if __name__ == "__main__":
    # Run with agent (AI-powered)
    asyncio.run(run_task())
    
    # Or run step-by-step (deterministic)
    # asyncio.run(run_steps())
`
  }

  private generateActionsCode(actions: RecordedAction[]): string {
    if (actions.length === 0) {
      return '        # No actions recorded'
    }

    const steps = actions.map((action, index) => {
      const stepNum = index + 1
      const comment = this.options.includeComments
        ? `        # Step ${stepNum}: ${action.type}${action.target?.tagName ? ` on <${action.target.tagName}>` : ''}`
        : ''
      const code = this.generateActionCode(action)
      return comment ? `${comment}\n${code}` : code
    }).join('\n\n')

    return `        # Step-by-step implementation
${steps}`
  }

  private generateActionCode(action: RecordedAction): string {
    switch (action.type) {
      case 'navigate':
        return `        # Navigate to URL
        page = await browser.get_current_page()
        await page.goto('${action.page.url}')
        await asyncio.sleep(2)  # Wait for load`

      case 'click': {
        const selector = this.convertToBrowserUseSelector(action.selector.primary)
        return `        # Click element
        await controller.click_element(
            browser=browser,
            selector='${selector}'
        )
        await asyncio.sleep(0.5)`
      }

      case 'input': {
        const inputSelector = this.convertToBrowserUseSelector(action.selector.primary)
        const value = (action.value || '').replace(/'/g, "\\'")
        return `        # Type text
        await controller.input_text(
            browser=browser,
            selector='${inputSelector}',
            text='${value}'
        )
        await asyncio.sleep(0.5)`
      }

      case 'scroll': {
        const scrollValue = action.value || '0'
        return `        # Scroll page
        page = await browser.get_current_page()
        await page.evaluate(f"window.scrollTo(0, ${scrollValue})")
        await asyncio.sleep(0.5)`
      }

      case 'wait': {
        const delayMs = parseInt(action.value || '1000') / 1000
        return `        # Wait ${delayMs}s
        await asyncio.sleep(${delayMs})`
      }

      case 'extract': {
        const fieldName = action.value || 'unknown'
        const extractSelector = this.convertToBrowserUseSelector(action.selector.primary)
        return `        # Extract ${fieldName}
        page = await browser.get_current_page()
        element = await page.query_selector('${extractSelector}')
        if element:
            ${fieldName} = await element.text_content()
            print(f"${fieldName}: {${fieldName}}")`
      }

      default:
        return `        # Unsupported action: ${action.type}`
    }
  }

  private convertToBrowserUseSelector(selector: string): string {
    // browser-use uses standard CSS selectors
    // Convert our format if needed
    return selector.replace(/"/g, '\\"')
  }

  private escapePythonString(str: string): string {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/'/g, "\\'")
      .replace(/\n/g, '\\n')
  }
}
