import { RecordedAction, ScriptGeneratorOptions } from '../types'

export interface PlaywrightGeneratorOptions extends ScriptGeneratorOptions {
  headless?: boolean
}

export class PlaywrightGenerator {
  private options: Required<PlaywrightGeneratorOptions>

  constructor(options: PlaywrightGeneratorOptions = {}) {
    this.options = {
      includeComments: true,
      useAsyncAwait: true,
      addDelays: true,
      headless: true,
      ...options,
    }
  }

  generate(profileId: string, prompt: string, actions: RecordedAction[]): string {
    const timestamp = new Date().toISOString()

    const header = `"""
AUTO-GENERATED by browser-use-codegen

Task: "${prompt.replace(/"/g, '\\"')}"
Generated: ${timestamp}
Profile: ${profileId}
Actions: ${actions.length}
"""

from playwright.sync_api import sync_playwright, Page


def run() -> dict:
    result = {}

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=${this.options.headless ? 'True' : 'False'})
        page = browser.new_page()

        try:
${this.generateActionsCode(actions)}

        finally:
            browser.close()

    return result


if __name__ == "__main__":
    import json
    output = run()
    print(json.dumps(output, indent=2, ensure_ascii=False))
`
    return header
  }

  private generateActionsCode(actions: RecordedAction[]): string {
    if (actions.length === 0) {
      return '            # No actions recorded\n            pass'
    }

    return actions
      .map((action, index) => {
        const stepComment = this.options.includeComments
          ? `            # Step ${index + 1}: ${action.type}${action.target?.tagName ? ` on <${action.target.tagName}>` : ''}${action.value ? ` (${action.value.substring(0, 30)}${action.value.length > 30 ? '...' : ''})` : ''}${action.screenshot ? `\n            # Screenshot: ${action.screenshot}` : ''}`
          : ''
        const code = this.generateActionCode(action)
        return stepComment ? `${stepComment}\n${code}` : code
      })
      .join('\n\n')
  }

  private generateActionCode(action: RecordedAction): string {
    switch (action.type) {
      case 'navigate':
        return `            page.goto('${action.page.url}', wait_until='networkidle')`

      case 'click':
        return this.generateClickCode(action)

      case 'input':
        return this.generateInputCode(action)

      case 'select':
        return this.generateSelectCode(action)

      case 'scroll':
        return this.generateScrollCode(action)

      case 'wait': {
        const ms = action.value ? parseInt(action.value) : 1000
        return `            page.wait_for_timeout(${ms})`
      }

      case 'extract':
        return this.generateExtractCode(action)

      default:
        return `            # Unsupported action type: ${action.type}`
    }
  }

  private buildLocator(action: RecordedAction): string {
    const primary = action.selector.primary.replace(/'/g, "\\'")
    const fallbacks = action.selector.fallbacks || []

    if (fallbacks.length === 0) {
      return `page.locator('${primary}')`
    }

    // Use first working selector via or_ chain
    const all = [primary, ...fallbacks.slice(0, 2)]
    return `page.locator('${all.map(s => s.replace(/'/g, "\\'")).join(", ")}')`
  }

  private generateClickCode(action: RecordedAction): string {
    const locator = this.buildLocator(action)
    const delay = this.options.addDelays ? '\n            page.wait_for_timeout(500)' : ''

    return `            ${locator}.click()${delay}`
  }

  private generateInputCode(action: RecordedAction): string {
    const value = action.value || ''
    const hasEnter = value.endsWith('[Enter]')
    const cleanValue = hasEnter ? value.slice(0, -7) : value
    const locator = this.buildLocator(action)

    let code = `            ${locator}.clear()\n            ${locator}.fill('${cleanValue.replace(/'/g, "\\'")}')`

    if (hasEnter) {
      code += `\n            ${locator}.press('Enter')`
    }

    if (this.options.addDelays) {
      code += `\n            page.wait_for_timeout(300)`
    }

    return code
  }

  private generateSelectCode(action: RecordedAction): string {
    const value = action.value || ''
    const locator = this.buildLocator(action)
    const delay = this.options.addDelays ? '\n            page.wait_for_timeout(300)' : ''

    return `            ${locator}.select_option('${value.replace(/'/g, "\\'")}')${delay}`
  }

  private generateScrollCode(action: RecordedAction): string {
    const scrollValue = action.value || '0'
    const isWindowScroll =
      action.selector.primary === 'body' || action.selector.primary === 'html'

    if (isWindowScroll) {
      return `            page.evaluate('window.scrollTo(0, ${scrollValue})')${this.options.addDelays ? '\n            page.wait_for_timeout(500)' : ''}`
    } else {
      const primary = action.selector.primary.replace(/'/g, "\\'")
      return `            page.evaluate('(s) => { const el = document.querySelector(s); if (el) el.scrollTop = ${scrollValue} }', '${primary}')${this.options.addDelays ? '\n            page.wait_for_timeout(500)' : ''}`
    }
  }

  private generateExtractCode(action: RecordedAction): string {
    const fieldName = action.value || 'unknown'
    const primary = action.selector.primary.replace(/'/g, "\\'")
    const fallbacks = action.selector.fallbacks || []
    const all = [primary, ...fallbacks.slice(0, 2)]

    return `            # Extract ${fieldName}
            ${fieldName}_el = None
            for _sel in [${all.map(s => `'${s.replace(/'/g, "\\'")}'`).join(', ')}]:
                try:
                    ${fieldName}_el = page.locator(_sel).first
                    break
                except Exception:
                    pass
            ${fieldName} = ${fieldName}_el.text_content() if ${fieldName}_el else None
            if ${fieldName}:
                result['${fieldName}'] = ${fieldName}.strip()`
  }
}
