import { RecordedAction, ScriptGeneratorOptions } from '../types'

export class ScriptGenerator {
  private options: ScriptGeneratorOptions

  constructor(options: ScriptGeneratorOptions = {}) {
    this.options = {
      includeComments: true,
      useAsyncAwait: true,
      addDelays: true,
      ...options,
    }
  }

  generate(
    profileId: string,
    prompt: string,
    actions: RecordedAction[]
  ): string {
    const timestamp = new Date().toISOString()
    const extractedFields = new Set<string>()

    // Identify extracted fields for interface generation
    actions.forEach((a) => {
      if (a.type === 'extract' && a.value) {
        extractedFields.add(a.value)
      }
    })

    const interfaceProps = Array.from(extractedFields)
      .map((field) => `  ${field}?: string | null`)
      .join('\n')

    const interfaceDef =
      extractedFields.size > 0
        ? `interface ScrapeResult {\n${interfaceProps}\n}`
        : 'type ScrapeResult = Record<string, any>'

    return `/**
 * AUTO-GENERATED by browser-use-codegen
 * 
 * Task: "${prompt.replace(/"/g, '\\"')}"
 * Generated: ${timestamp}
 * Profile: ${profileId}
 * Actions: ${actions.length}
 */

import { Page, ElementHandle, Browser } from 'puppeteer-core'

${interfaceDef}

export async function execute(page: Page): Promise<ScrapeResult> {
  const result: ScrapeResult = {}
  
  // Helper for delays
  const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))

${this.generateActionsCode(actions)}

  return result
}

/**
 * Run the automation with a browser instance
 */
export async function runWithBrowser(
  browser: Browser,
  options: { slowMo?: number } = {}
): Promise<ScrapeResult> {
  const page = await browser.newPage()
  
  if (options.slowMo) {
    // Add small delay between actions for visibility
    const originalGoto = page.goto.bind(page)
    page.goto = async (url: string, opts?: any) => {
      await delay(options.slowMo!)
      return originalGoto(url, opts)
    }
  }

  try {
    return await execute(page)
  } finally {
    await page.close()
  }
}

// Standalone execution (requires PUPPETEER_WS_ENDPOINT env var)
export default async function main() {
  const wsEndpoint = process.env.PUPPETEER_WS_ENDPOINT
  
  if (!wsEndpoint) {
    console.error('Error: PUPPETEER_WS_ENDPOINT environment variable is required')
    console.error('Example: PUPPETEER_WS_ENDPOINT=ws://localhost:9222 node script.js')
    process.exit(1)
  }

  const puppeteer = await import('puppeteer-core')
  
  const browser = await puppeteer.connect({
    browserWSEndpoint: wsEndpoint,
  })
  
  try {
    console.log('Running automation...')
    const result = await runWithBrowser(browser)
    console.log('\\n✅ Result:')
    console.log(JSON.stringify(result, null, 2))
    return result
  } catch (error) {
    console.error('\\n❌ Error:', error)
    throw error
  } finally {
    await browser.disconnect()
  }
}

// Run if executed directly
if (require.main === module) {
  main().catch(err => {
    console.error('Fatal error:', err)
    process.exit(1)
  })
}
`
  }

  private generateActionsCode(actions: RecordedAction[]): string {
    if (actions.length === 0) {
      return '  // No actions recorded\n  console.log("No actions to perform")'
    }

    return actions
      .map((action, index) => {
        const screenshotComment = action.screenshot ? `\n  // Screenshot: ${action.screenshot}` : ''
        const stepComment = this.options.includeComments
          ? `  // Step ${index + 1}: ${action.type}${action.target?.tagName ? ` on <${action.target.tagName}>` : ''}${action.value ? ` (${action.value.substring(0, 30)}${action.value.length > 30 ? '...' : ''})` : ''}${screenshotComment}`
          : ''
        const code = this.generateActionCode(action)
        return stepComment ? `${stepComment}\n${code}` : code
      })
      .join('\n\n')
  }

  private generateActionCode(action: RecordedAction): string {
    switch (action.type) {
      case 'navigate':
        return `  await page.goto('${action.page.url}', { waitUntil: 'networkidle2' })`

      case 'click':
        return this.generateClickCode(action)

      case 'input':
        return this.generateInputCode(action)

      case 'select':
        return this.generateSelectCode(action)

      case 'scroll':
        return this.generateScrollCode(action)

      case 'wait':
        const delayMs = action.value ? parseInt(action.value) : 1000
        return `  await delay(${delayMs})`

      case 'extract':
        return this.generateExtractCode(action)

      default:
        return `  // Unsupported action type: ${action.type}`
    }
  }

  private generateSelectorLogic(
    action: RecordedAction,
    varName: string
  ): string {
    const primary = action.selector.primary
    const fallbacks = action.selector.fallbacks || []
    const allSelectors = [primary, ...fallbacks.slice(0, 2)] // Limit to 3 selectors
      .map((s) => `'${s.replace(/'/g, "\\'")}'`)
      .join(', ')

    return `{
    const selectors = [${allSelectors}]
    let ${varName}: ElementHandle<Element> | null = null
    for (const selector of selectors) {
      try {
        await page.waitForSelector(selector, { timeout: 5000 })
        ${varName} = await page.$(selector)
        if (${varName}) break
      } catch (e) {
        // Try next selector
      }
    }
    if (!${varName}) {
      console.warn('Element not found for action: ${action.type}')
      // Skip this action and continue
    } else`
  }

  private generateClickCode(action: RecordedAction): string {
    const selectorBlock = this.generateSelectorLogic(action, 'element')
    const delay = this.options.addDelays ? '\n      await delay(500)' : ''
    
    return `  ${selectorBlock} {${delay}
      await element.click()
    }
  }`
  }

  private generateInputCode(action: RecordedAction): string {
    const value = action.value || ''
    const hasEnter = value.endsWith('[Enter]')
    const cleanValue = hasEnter ? value.slice(0, -7) : value
    
    const selectorBlock = this.generateSelectorLogic(action, 'element')
    
    let code = `  ${selectorBlock} {
      await element.click({ clickCount: 3 }) // Select all
      await delay(100)
      await element.type('${cleanValue.replace(/'/g, "\\'")}', { delay: 50 })`
    
    if (hasEnter) {
      code += `\n      await element.press('Enter')`
    }
    
    if (this.options.addDelays) {
      code += `\n      await delay(500)`
    }
    
    code += `\n    }\n  }`
    
    return code
  }

  private generateSelectCode(action: RecordedAction): string {
    const value = action.value || ''
    const selectorBlock = this.generateSelectorLogic(action, 'element')
    
    return `  ${selectorBlock} {
      await element.select('${value.replace(/'/g, "\\'")}')${this.options.addDelays ? '\n      await delay(500)' : ''}
    }
  }`
  }

  private generateScrollCode(action: RecordedAction): string {
    const scrollValue = action.value || '0'
    const isWindowScroll = action.selector.primary === 'body' || 
                           action.selector.primary === 'html'
    
    if (isWindowScroll) {
      return `  await page.evaluate(() => {
    window.scrollTo(0, ${scrollValue})
  })${this.options.addDelays ? '\n  await delay(500)' : ''}`
    } else {
      const primary = action.selector.primary.replace(/'/g, "\\'")
      return `  await page.evaluate((selector) => {
    const el = document.querySelector(selector)
    if (el) el.scrollTop = ${scrollValue}
  }, '${primary}')${this.options.addDelays ? '\n  await delay(500)' : ''}`
    }
  }

  private generateExtractCode(action: RecordedAction): string {
    const fieldName = action.value || 'unknown'
    const primary = action.selector.primary
    const fallbacks = action.selector.fallbacks || []
    const allSelectors = [primary, ...fallbacks.slice(0, 2)]

    return `  // Extract ${fieldName}
  const ${fieldName}Val = await page.evaluate(function(selectors) {
    var el = null
    for (var i = 0; i < selectors.length; i++) {
      el = document.querySelector(selectors[i])
      if (el) break
    }
    if (!el) return null
    
    // Try to get meaningful content
    var value = el.textContent || el.value || el.getAttribute('content') || ''
    return value.replace(/^[\\s\\n\\r]+|[\\s\\n\\r]+$/g, '')
  }, ${JSON.stringify(allSelectors)})
  
  if (${fieldName}Val) {
    result['${fieldName}'] = ${fieldName}Val
  }`
  }
}
