import { RecordedAction, ScriptGeneratorOptions } from '../types'

export interface SeleniumGeneratorOptions extends ScriptGeneratorOptions {
  headless?: boolean
}

export class SeleniumGenerator {
  private options: Required<SeleniumGeneratorOptions>
  private needsKeys = false
  private needsSelect = false

  constructor(options: SeleniumGeneratorOptions = {}) {
    this.options = {
      includeComments: true,
      useAsyncAwait: true,
      addDelays: true,
      headless: false,
      ...options,
    }
  }

  generate(profileId: string, prompt: string, actions: RecordedAction[]): string {
    const timestamp = new Date().toISOString()

    // Scan actions to decide which imports to include
    this.needsKeys = actions.some(a => a.type === 'input' && a.value?.includes('[Enter]'))
    this.needsSelect = actions.some(a => a.type === 'select')

    const extraImports = [
      this.needsKeys ? 'from selenium.webdriver.common.keys import Keys' : null,
      this.needsSelect ? 'from selenium.webdriver.support.ui import Select' : null,
    ]
      .filter(Boolean)
      .join('\n')

    return `"""
AUTO-GENERATED by browser-use-codegen

Task: "${prompt.replace(/"/g, '\\"')}"
Generated: ${timestamp}
Profile: ${profileId}
Actions: ${actions.length}
"""

import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options as ChromeOptions
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC${extraImports ? '\n' + extraImports : ''}


def run() -> dict:
    result = {}

    options = ChromeOptions()
${this.options.headless ? "    options.add_argument('--headless')\n    options.add_argument('--disable-gpu')" : '    # options.add_argument(\'--headless\')  # Uncomment for headless mode'}
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')

    driver = webdriver.Chrome(options=options)
    driver.implicitly_wait(10)

    try:
${this.generateActionsCode(actions)}

    finally:
        driver.quit()

    return result


if __name__ == "__main__":
    import json
    output = run()
    print(json.dumps(output, indent=2, ensure_ascii=False))
`
  }

  private generateActionsCode(actions: RecordedAction[]): string {
    if (actions.length === 0) {
      return '        # No actions recorded\n        pass'
    }

    return actions
      .map((action, index) => {
        const screenshotComment = action.screenshot ? `\n        # Screenshot: ${action.screenshot}` : ''
        const stepComment = this.options.includeComments
          ? `        # Step ${index + 1}: ${action.type}${action.target?.tagName ? ` on <${action.target.tagName}>` : ''}${action.value ? ` (${action.value.substring(0, 30)}${action.value.length > 30 ? '...' : ''})` : ''}${screenshotComment}`
          : ''
        const code = this.generateActionCode(action)
        return stepComment ? `${stepComment}\n${code}` : code
      })
      .join('\n\n')
  }

  private generateActionCode(action: RecordedAction): string {
    switch (action.type) {
      case 'navigate':
        return `        driver.get('${action.page.url}')`

      case 'click':
        return this.generateClickCode(action)

      case 'input':
        return this.generateInputCode(action)

      case 'select':
        return this.generateSelectCode(action)

      case 'scroll':
        return this.generateScrollCode(action)

      case 'wait': {
        const ms = action.value ? parseInt(action.value) : 1000
        const seconds = ms / 1000
        return `        time.sleep(${seconds % 1 === 0 ? seconds.toFixed(0) : seconds})`
      }

      case 'extract':
        return this.generateExtractCode(action)

      default:
        return `        # Unsupported action type: ${action.type}`
    }
  }

  private selectorToBy(selector: string): { by: string; value: string } {
    if (selector.startsWith('#')) {
      return { by: 'By.ID', value: selector.slice(1) }
    }
    if (selector.startsWith('[aria-label="')) {
      const match = selector.match(/\[aria-label="(.+?)"\]/)
      if (match) return { by: 'By.CSS_SELECTOR', value: selector }
    }
    // CSS selectors (class, attribute, compound)
    return { by: 'By.CSS_SELECTOR', value: selector }
  }

  private generateClickCode(action: RecordedAction): string {
    const primary = action.selector.primary
    const fallbacks = action.selector.fallbacks || []
    const { by, value } = this.selectorToBy(primary)
    const delay = this.options.addDelays ? '\n        time.sleep(0.5)' : ''

    if (fallbacks.length === 0) {
      return `        driver.find_element(${by}, '${value.replace(/'/g, "\\'")}').click()${delay}`
    }

    const allSelectors = [{ by, value }, ...fallbacks.slice(0, 2).map(s => this.selectorToBy(s))]
    const tryBlocks = allSelectors
      .map((sel, i) =>
        i === 0
          ? `        try:\n            driver.find_element(${sel.by}, '${sel.value.replace(/'/g, "\\'")}').click()`
          : `        except Exception:\n            try:\n                driver.find_element(${sel.by}, '${sel.value.replace(/'/g, "\\'")}').click()`
      )
      .join('\n')

    return `${tryBlocks}
        except Exception:
            pass${delay}`
  }

  private generateInputCode(action: RecordedAction): string {
    const value = action.value || ''
    const hasEnter = value.endsWith('[Enter]')
    const cleanValue = hasEnter ? value.slice(0, -7) : value
    const { by, value: sel } = this.selectorToBy(action.selector.primary)

    let code = `        _el = driver.find_element(${by}, '${sel.replace(/'/g, "\\'")}')
        _el.clear()
        _el.send_keys('${cleanValue.replace(/'/g, "\\'")}')`

    if (hasEnter) {
      code += `\n        _el.send_keys(Keys.RETURN)`
    }

    if (this.options.addDelays) {
      code += `\n        time.sleep(0.3)`
    }

    return code
  }

  private generateSelectCode(action: RecordedAction): string {
    const value = action.value || ''
    const { by, value: sel } = this.selectorToBy(action.selector.primary)
    const delay = this.options.addDelays ? '\n        time.sleep(0.3)' : ''

    return `        Select(driver.find_element(${by}, '${sel.replace(/'/g, "\\'")}'))\\\n            .select_by_value('${value.replace(/'/g, "\\'")}')${delay}`
  }

  private generateScrollCode(action: RecordedAction): string {
    const scrollValue = action.value || '0'
    const isWindowScroll =
      action.selector.primary === 'body' || action.selector.primary === 'html'

    if (isWindowScroll) {
      return `        driver.execute_script('window.scrollTo(0, ${scrollValue})')${this.options.addDelays ? '\n        time.sleep(0.5)' : ''}`
    } else {
      const sel = action.selector.primary.replace(/'/g, "\\'")
      return `        _scroll_el = driver.find_element(By.CSS_SELECTOR, '${sel}')
        driver.execute_script('arguments[0].scrollTop = ${scrollValue}', _scroll_el)${this.options.addDelays ? '\n        time.sleep(0.5)' : ''}`
    }
  }

  private generateExtractCode(action: RecordedAction): string {
    const fieldName = action.value || 'unknown'
    const primary = action.selector.primary
    const fallbacks = action.selector.fallbacks || []
    const all = [primary, ...fallbacks.slice(0, 2)]

    return `        # Extract ${fieldName}
        _${fieldName}_el = None
        for _sel in [${all.map(s => `'${s.replace(/'/g, "\\'")}'`).join(', ')}]:
            try:
                _${fieldName}_el = driver.find_element(By.CSS_SELECTOR, _sel)
                break
            except Exception:
                pass
        if _${fieldName}_el:
            result['${fieldName}'] = _${fieldName}_el.text.strip()`
  }
}
