import { BrowserUseGenerator } from '../lib/BrowserUseGenerator'
import { RecordedAction } from '../types'
import * as fs from 'fs'
import * as path from 'path'

describe('BrowserUseGenerator E2E', () => {
  let generator: BrowserUseGenerator
  let sampleActions: RecordedAction[]

  beforeEach(() => {
    generator = new BrowserUseGenerator()

    // Load fixture actions
    const fixturesPath = path.join(__dirname, 'fixtures', 'actions.json')
    sampleActions = JSON.parse(fs.readFileSync(fixturesPath, 'utf-8'))
  })

  describe('generate()', () => {
    it('should generate valid Python browser-use script', () => {
      const script = generator.generate('test-profile', 'Test automation', sampleActions)

      expect(script).toContain('AUTO-GENERATED by browser-use-codegen')
      expect(script).toContain('Test automation')
      expect(script).toContain('test-profile')
      expect(script).toContain('import asyncio')
      expect(script).toContain('from browser_use import Agent, Browser, BrowserConfig')
      expect(script).toContain('from langchain_openai import ChatOpenAI')
    })

    it('should include task description in docstring', () => {
      const script = generator.generate('test-profile', 'Extract product details', sampleActions)

      expect(script).toContain('Extract product details')
      expect(script).toMatch(/"""\s*Extract product details\s*"""/)
    })

    it('should include metadata in header', () => {
      const script = generator.generate('my-profile', 'My task', sampleActions)

      expect(script).toContain('Task: "My task"')
      expect(script).toContain('Profile: my-profile')
      expect(script).toContain('Actions: ' + sampleActions.length)
      expect(script).toMatch(/Generated: \d{4}-\d{2}-\d{2}/)
    })

    it('should handle empty actions array', () => {
      const script = generator.generate('test-profile', 'Test', [])

      expect(script).toContain('# No actions recorded')
      expect(script).toContain('async def run_task()')
    })
  })

  describe('Python script structure', () => {
    it('should include run_task function with agent', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('async def run_task()')
      expect(script).toContain('browser = Browser(config=BrowserConfig(')
      expect(script).toContain('llm = ChatOpenAI(model="gpt-4o", temperature=0.0)')
      expect(script).toContain('agent = Agent(')
      expect(script).toContain('result = await agent.run()')
    })

    it('should include run_steps alternative function', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('async def run_steps()')
      expect(script).toContain('Step-by-step implementation')
      expect(script).toContain('from browser_use import Controller')
      expect(script).toContain('controller = Controller()')
    })

    it('should include main execution block', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('if __name__ == "__main__":')
      expect(script).toContain('asyncio.run(run_task())')
    })

    it('should include requirements comment', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('pip install browser-use')
    })
  })

  describe('action type generation', () => {
    it('should generate navigate action', () => {
      const navigateAction: RecordedAction = {
        type: 'navigate',
        timestamp: Date.now(),
        selector: { primary: 'body', fallbacks: [] },
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Navigate test', [navigateAction])

      expect(script).toContain('# Navigate to URL')
      expect(script).toContain('await page.goto(\'https://example.com\')')
      expect(script).toContain('await asyncio.sleep(2)')
    })

    it('should generate click action with controller', () => {
      const clickAction: RecordedAction = {
        type: 'click',
        timestamp: Date.now(),
        selector: { primary: '[data-testid="button"]', fallbacks: [] },
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Click test', [clickAction])

      expect(script).toContain('# Click element')
      expect(script).toContain('await controller.click_element(')
      expect(script).toContain('browser=browser')
      // Python string escapes quotes: selector='[data-testid=\"button\"]'
      expect(script).toContain('[data-testid=')
      expect(script).toContain('button')
    })

    it('should generate input action', () => {
      const inputAction: RecordedAction = {
        type: 'input',
        timestamp: Date.now(),
        selector: { primary: '#email', fallbacks: [] },
        value: 'test@example.com',
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Input test', [inputAction])

      expect(script).toContain('# Type text')
      expect(script).toContain('await controller.input_text(')
      expect(script).toContain('selector=\'#email\'')
      expect(script).toContain('text=\'test@example.com\'')
    })

    it('should generate scroll action', () => {
      const scrollAction: RecordedAction = {
        type: 'scroll',
        timestamp: Date.now(),
        selector: { primary: 'body', fallbacks: [] },
        value: '500',
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Scroll test', [scrollAction])

      expect(script).toContain('# Scroll page')
      expect(script).toContain('await page.evaluate(f"window.scrollTo(0, 500)")')
    })

    it('should generate wait action', () => {
      const waitAction: RecordedAction = {
        type: 'wait',
        timestamp: Date.now(),
        selector: { primary: 'body', fallbacks: [] },
        value: '2000',
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Wait test', [waitAction])

      expect(script).toContain('# Wait 2s')
      expect(script).toContain('await asyncio.sleep(2')
    })

    it('should generate extract action', () => {
      const extractAction: RecordedAction = {
        type: 'extract',
        timestamp: Date.now(),
        selector: { primary: '.price', fallbacks: [] },
        value: 'productPrice',
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Extract test', [extractAction])

      expect(script).toContain('# Extract productPrice')
      expect(script).toContain('element = await page.query_selector(\'.price\')')
      expect(script).toContain('productPrice = await element.text_content()')
      expect(script).toContain('print(f"productPrice: {productPrice}")')
    })
  })

  describe('Python syntax and formatting', () => {
    it('should use proper Python indentation', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      // Check 4-space indentation in function
      expect(script).toMatch(/^    browser = Browser/m)
      expect(script).toMatch(/^        # Step/m)
    })

    it('should use Python async/await syntax', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('async def')
      expect(script).toContain('await ')
      expect(script).toContain('asyncio.run(')
    })

    it('should include proper Python imports', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('import asyncio')
      expect(script).toContain('from browser_use import Agent, Browser, BrowserConfig')
      expect(script).toContain('from langchain_openai import ChatOpenAI')
    })
  })

  describe('special character handling', () => {
    it('should escape quotes in task description', () => {
      const script = generator.generate('test-profile', 'Test "quotes" in task', sampleActions)

      expect(script).toContain('Test \\"quotes\\" in task')
    })

    it('should escape quotes in input values', () => {
      const inputAction: RecordedAction = {
        type: 'input',
        timestamp: Date.now(),
        selector: { primary: 'input', fallbacks: [] },
        value: "It's a test",
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Test', [inputAction])

      expect(script).toContain("It\\'s a test")
    })

    it('should handle newlines in strings', () => {
      const script = generator.generate('test-profile', 'Line 1\nLine 2', sampleActions)

      expect(script).toContain('Line 1\\nLine 2')
    })

    it('should handle backslashes in strings', () => {
      const script = generator.generate('test-profile', 'Path: C:\\Users\\test', sampleActions)

      expect(script).toContain('C:\\\\Users\\\\test')
    })
  })

  describe('selector conversion', () => {
    it('should convert CSS selectors properly', () => {
      const action: RecordedAction = {
        type: 'click',
        timestamp: Date.now(),
        selector: { primary: 'button[data-test="submit"]', fallbacks: [] },
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Test', [action])

      // Python escapes the quotes inside the selector string
      expect(script).toContain('button[data-test=')
      expect(script).toContain('submit')
    })

    it('should handle complex selectors', () => {
      const action: RecordedAction = {
        type: 'click',
        timestamp: Date.now(),
        selector: { primary: 'div.class > span:nth-child(2)', fallbacks: [] },
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Test', [action])

      expect(script).toContain('div.class > span:nth-child(2)')
    })
  })

  describe('step comments', () => {
    it('should include step numbers when comments enabled', () => {
      const generatorWithComments = new BrowserUseGenerator({ includeComments: true })
      const script = generatorWithComments.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('# Step 1:')
      expect(script).toContain('# Step 2:')
    })

    it('should include action type in comments', () => {
      const generatorWithComments = new BrowserUseGenerator({ includeComments: true })
      const script = generatorWithComments.generate('test-profile', 'Test', sampleActions)

      expect(script).toMatch(/# Step \d+: click/)
      expect(script).toMatch(/# Step \d+: input/)
    })

    it('should exclude step comments when disabled', () => {
      const generatorNoComments = new BrowserUseGenerator({ includeComments: false })
      const script = generatorNoComments.generate('test-profile', 'Test', sampleActions)

      expect(script).not.toContain('# Step 1:')
      // But should still have action-specific comments
      expect(script).toContain('# Navigate to URL')
    })
  })

  describe('complete workflow generation', () => {
    it('should generate complete script with all action types', () => {
      const script = generator.generate('test-profile', 'Complete test', sampleActions)

      // Check all action types are present
      expect(script).toContain('# Navigate to URL')
      expect(script).toContain('# Click element')
      expect(script).toContain('# Type text')
      expect(script).toContain('# Scroll page')
      expect(script).toContain('# Wait')
      expect(script).toContain('# Extract')
    })

    it('should maintain action order', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      const stepMatches = script.match(/# Step \d+:/g) || []
      expect(stepMatches.length).toBe(sampleActions.length)
    })
  })

  describe('browser-use compatibility', () => {
    it('should use browser-use Controller API', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('controller = Controller()')
      expect(script).toContain('await controller.click_element(')
      expect(script).toContain('await controller.input_text(')
    })

    it('should use browser-use Agent API', () => {
      const script = generator.generate('test-profile', 'Test task', sampleActions)

      expect(script).toContain('agent = Agent(')
      expect(script).toContain('task="""Test task"""')
      expect(script).toContain('llm=llm')
      expect(script).toContain('browser=browser')
      expect(script).toContain('use_vision=True')
    })

    it('should configure BrowserConfig properly', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('Browser(config=BrowserConfig(')
      expect(script).toContain('headless=False')
    })
  })

  describe('error handling', () => {
    it('should handle unsupported action types', () => {
      const unsupportedAction: RecordedAction = {
        type: 'unsupported' as any,
        timestamp: Date.now(),
        selector: { primary: 'div', fallbacks: [] },
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Test', [unsupportedAction])

      expect(script).toContain('# Unsupported action: unsupported')
    })
  })

  describe('output validation', () => {
    it('should generate valid Python syntax structure', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      // Check for proper indentation
      expect(script).toMatch(/^async def run_task\(\):/m)
      expect(script).toMatch(/^    /m) // 4-space indent

      // Check for proper async blocks
      expect(script).toMatch(/async def \w+\(\):/)

      // Check for proper docstrings
      expect(script).toMatch(/"""\n.*\n.*"""/s)
    })

    it('should include proper error handling structure', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('try:')
      expect(script).toContain('finally:')
      expect(script).toContain('await browser.close()')
    })
  })
})
