import { ActionRecorder } from '../lib/ActionRecorder'
import { ScriptGenerator } from '../lib/ScriptGenerator'
import { BrowserUseGenerator } from '../lib/BrowserUseGenerator'
import { RecordedAction } from '../types'

describe('Full Flow E2E', () => {
  let mockPage: any
  let recorder: ActionRecorder
  let scriptGenerator: ScriptGenerator
  let browserUseGenerator: BrowserUseGenerator
  let exposedFunctions: Map<string, Function>

  beforeEach(() => {
    exposedFunctions = new Map()

    mockPage = {
      url: jest.fn().mockReturnValue('https://marketplace.facebook.com'),
      title: jest.fn().mockResolvedValue('Facebook Marketplace'),
      exposeFunction: jest.fn().mockImplementation((name: string, fn: Function) => {
        exposedFunctions.set(name, fn)
        return Promise.resolve()
      }),
      evaluateOnNewDocument: jest.fn().mockResolvedValue(undefined),
      evaluate: jest.fn().mockResolvedValue(undefined),
    }

    recorder = new ActionRecorder(mockPage, { debug: false })
    scriptGenerator = new ScriptGenerator({
      includeComments: true,
      addDelays: true,
    })
    browserUseGenerator = new BrowserUseGenerator({
      includeComments: true,
      addDelays: true,
    })
  })

  describe('Complete Workflow: Record -> Generate Scripts', () => {
    it('should record actions and generate both Puppeteer and Browser-Use scripts', async () => {
      // Step 1: Start recording
      await recorder.start()

      // Verify recording started
      expect(mockPage.exposeFunction).toHaveBeenCalled()
      expect(recorder.getActions().length).toBeGreaterThan(0)

      // Step 2: Simulate user interactions
      const bridge = exposedFunctions.get('__recordActionBridge')!

      // Navigate to search
      mockPage.url.mockReturnValue('https://marketplace.facebook.com/search')
      mockPage.title.mockResolvedValue('Search - Marketplace')

      // Click search input
      await bridge(JSON.stringify({
        type: 'click',
        selector: {
          primary: '[data-testid="search-input"]',
          fallbacks: ['#search', 'input[placeholder="Search Marketplace"]'],
        },
        target: {
          tagName: 'input',
          id: 'search',
          ariaLabel: 'Search Marketplace',
        },
        page: {
          url: 'https://marketplace.facebook.com/search',
          title: 'Search - Marketplace',
        },
      }))

      // Type search query
      await bridge(JSON.stringify({
        type: 'input',
        selector: {
          primary: '[data-testid="search-input"]',
          fallbacks: ['#search'],
        },
        value: 'toyota camry[Enter]',
        target: {
          tagName: 'input',
          id: 'search',
        },
        page: {
          url: 'https://marketplace.facebook.com/search',
          title: 'Search - Marketplace',
        },
      }))

      // Wait for results
      await recorder.addWaitAction(2000)

      // Scroll to load more
      await bridge(JSON.stringify({
        type: 'scroll',
        selector: { primary: 'body', fallbacks: [] },
        value: '1000',
        page: {
          url: 'https://marketplace.facebook.com/search?query=toyota+camry',
          title: 'Search Results',
        },
      }))

      // Extract first result title
      await recorder.addExtractAction('vehicleTitle', '[data-testid="listing-title"]')

      // Extract price
      await recorder.addExtractAction('vehiclePrice', '[data-testid="listing-price"]')

      // Step 3: Stop recording
      const actions = await recorder.stop()

      // Verify all actions recorded
      expect(actions.length).toBeGreaterThan(6)
      expect(actions.filter(a => a.type === 'click').length).toBe(1)
      expect(actions.filter(a => a.type === 'input').length).toBe(1)
      expect(actions.filter(a => a.type === 'wait').length).toBe(1)
      expect(actions.filter(a => a.type === 'scroll').length).toBe(1)
      expect(actions.filter(a => a.type === 'extract').length).toBe(2)

      // Step 4: Generate Puppeteer script
      const puppeteerScript = scriptGenerator.generate(
        'marketplace-profile-001',
        'Search for Toyota Camry on Facebook Marketplace and extract vehicle details',
        actions
      )

      // Verify Puppeteer script
      expect(puppeteerScript).toContain('AUTO-GENERATED by browser-use-codegen')
      expect(puppeteerScript).toContain('marketplace-profile-001')
      expect(puppeteerScript).toContain('Search for Toyota Camry')
      expect(puppeteerScript).toContain('import { Page, ElementHandle, Browser } from \'puppeteer-core\'')
      expect(puppeteerScript).toContain('export async function execute(page: Page)')
      expect(puppeteerScript).toContain('vehicleTitle')
      expect(puppeteerScript).toContain('vehiclePrice')
      expect(puppeteerScript).toContain('[data-testid="search-input"]')
      expect(puppeteerScript).toContain('toyota camry')
      expect(puppeteerScript).toContain('await element.press(\'Enter\')')

      // Step 5: Generate Browser-Use script
      const browserUseScript = browserUseGenerator.generate(
        'marketplace-profile-001',
        'Search for Toyota Camry on Facebook Marketplace and extract vehicle details',
        actions
      )

      // Verify Browser-Use script
      expect(browserUseScript).toContain('AUTO-GENERATED by browser-use-codegen')
      expect(browserUseScript).toContain('marketplace-profile-001')
      expect(browserUseScript).toContain('Search for Toyota Camry')
      expect(browserUseScript).toContain('import asyncio')
      expect(browserUseScript).toContain('from browser_use import Agent, Browser, BrowserConfig')
      expect(browserUseScript).toContain('async def run_task()')
      expect(browserUseScript).toContain('async def run_steps()')
      expect(browserUseScript).toContain('vehicleTitle')
      expect(browserUseScript).toContain('vehiclePrice')

      // Verify both scripts have consistent action count
      const puppeteerStepMatches = puppeteerScript.match(/\/\/ Step \d+:/g) || []
      const pythonStepMatches = browserUseScript.match(/# Step \d+:/g) || []
      expect(puppeteerStepMatches.length).toBe(actions.length)
      expect(pythonStepMatches.length).toBe(actions.length)
    })
  })

  describe('Real-world scenarios', () => {
    it('should handle form submission workflow', async () => {
      await recorder.start()

      const bridge = exposedFunctions.get('__recordActionBridge')!

      // Navigate to form
      mockPage.url.mockReturnValue('https://example.com/contact')
      mockPage.title.mockResolvedValue('Contact Us')

      // Fill name
      await bridge(JSON.stringify({
        type: 'input',
        selector: { primary: '#name', fallbacks: ['input[name="name"]'] },
        value: 'John Doe',
      }))

      // Fill email
      await bridge(JSON.stringify({
        type: 'input',
        selector: { primary: '#email', fallbacks: ['input[type="email"]'] },
        value: 'john@example.com',
      }))

      // Select country
      await bridge(JSON.stringify({
        type: 'select',
        selector: { primary: '#country', fallbacks: [] },
        value: 'US',
      }))

      // Fill message
      await bridge(JSON.stringify({
        type: 'input',
        selector: { primary: '#message', fallbacks: ['textarea'] },
        value: 'This is a test message',
      }))

      // Click submit
      await bridge(JSON.stringify({
        type: 'click',
        selector: { primary: 'button[type="submit"]', fallbacks: [] },
      }))

      const actions = await recorder.stop()

      // Generate scripts
      const puppeteerScript = scriptGenerator.generate(
        'form-profile',
        'Fill and submit contact form',
        actions
      )
      const browserUseScript = browserUseGenerator.generate(
        'form-profile',
        'Fill and submit contact form',
        actions
      )

      // Verify form fields in Puppeteer script
      expect(puppeteerScript).toContain('John Doe')
      expect(puppeteerScript).toContain('john@example.com')
      expect(puppeteerScript).toContain('This is a test message')
      expect(puppeteerScript).toContain('await element.select(\'US\')')

      // Verify form fields in Browser-Use script
      expect(browserUseScript).toContain('John Doe')
      expect(browserUseScript).toContain('john@example.com')
      expect(browserUseScript).toContain('This is a test message')
    })

    it('should handle data extraction workflow', async () => {
      await recorder.start()

      const bridge = exposedFunctions.get('__recordActionBridge')!

      // Navigate to product page
      mockPage.url.mockReturnValue('https://shop.example.com/product/123')

      // Add extraction actions
      await recorder.addExtractAction('productTitle', 'h1.product-title')
      await recorder.addExtractAction('productPrice', '.price-value')
      await recorder.addExtractAction('productDescription', '.description')
      await recorder.addExtractAction('productRating', '.rating-score')

      const actions = await recorder.stop()

      // Generate Puppeteer script
      const puppeteerScript = scriptGenerator.generate(
        'scraper-profile',
        'Extract product information',
        actions
      )

      // Verify interface generation for extracted fields
      expect(puppeteerScript).toContain('interface ScrapeResult')
      expect(puppeteerScript).toContain('productTitle?: string | null')
      expect(puppeteerScript).toContain('productPrice?: string | null')
      expect(puppeteerScript).toContain('productDescription?: string | null')
      expect(puppeteerScript).toContain('productRating?: string | null')

      // Verify extraction code
      expect(puppeteerScript).toContain('// Extract productTitle')
      expect(puppeteerScript).toContain('result[\'productTitle\']')

      // Generate Browser-Use script
      const browserUseScript = browserUseGenerator.generate(
        'scraper-profile',
        'Extract product information',
        actions
      )

      // Verify extraction in Python
      expect(browserUseScript).toContain('# Extract productTitle')
      expect(browserUseScript).toContain('productTitle = await element.text_content()')
    })

    it('should handle navigation and pagination workflow', async () => {
      await recorder.start()

      const bridge = exposedFunctions.get('__recordActionBridge')!

      // Start on page 1
      mockPage.url.mockReturnValue('https://example.com/items?page=1')

      // Extract items from page 1
      await recorder.addExtractAction('item1', '.item:nth-child(1) .title')

      // Click next button
      await bridge(JSON.stringify({
        type: 'click',
        selector: { primary: '.pagination .next', fallbacks: ['a[rel="next"]'] },
      }))

      // Wait for navigation
      await recorder.addWaitAction(1000)

      // Extract items from page 2
      await recorder.addExtractAction('item2', '.item:nth-child(1) .title')

      const actions = await recorder.stop()

      const puppeteerScript = scriptGenerator.generate(
        'pagination-profile',
        'Navigate through paginated results',
        actions
      )

      // Verify pagination flow
      expect(puppeteerScript).toContain('// Extract item1')
      expect(puppeteerScript).toContain('.pagination .next')
      expect(puppeteerScript).toContain('await delay(1000)')
      expect(puppeteerScript).toContain('// Extract item2')
    })
  })

  describe('Script validation', () => {
    it('should generate syntactically valid TypeScript', async () => {
      await recorder.start()

      const bridge = exposedFunctions.get('__recordActionBridge')!

      await bridge(JSON.stringify({
        type: 'click',
        selector: { primary: 'button', fallbacks: [] },
      }))

      const actions = await recorder.stop()
      const script = scriptGenerator.generate('test', 'Test', actions)

      // Check balanced braces
      const openBraces = (script.match(/{/g) || []).length
      const closeBraces = (script.match(/}/g) || []).length
      expect(openBraces).toBe(closeBraces)

      // Check balanced parentheses
      const openParens = (script.match(/\(/g) || []).length
      const closeParens = (script.match(/\)/g) || []).length
      expect(openParens).toBe(closeParens)

      // Check imports
      expect(script).toContain('import {')

      // Check exports
      expect(script).toContain('export async function')
    })

    it('should generate syntactically valid Python', async () => {
      await recorder.start()

      const bridge = exposedFunctions.get('__recordActionBridge')!

      await bridge(JSON.stringify({
        type: 'click',
        selector: { primary: 'button', fallbacks: [] },
      }))

      const actions = await recorder.stop()
      const script = browserUseGenerator.generate('test', 'Test', actions)

      // Check Python structure
      expect(script).toMatch(/^import /m)
      expect(script).toMatch(/^from .* import /m)
      expect(script).toMatch(/^async def \w+\(\):/m)
      expect(script).toMatch(/^if __name__ == "__main__":/m)

      // Check indentation consistency (4 spaces)
      const lines = script.split('\n')
      const indentedLines = lines.filter(line => line.startsWith('    '))
      expect(indentedLines.length).toBeGreaterThan(0)
    })
  })

  describe('Edge cases', () => {
    it('should handle empty recording gracefully', async () => {
      await recorder.start()
      const actions = await recorder.stop()

      // Should only have initial navigate action
      expect(actions.length).toBe(1)
      expect(actions[0].type).toBe('navigate')

      const puppeteerScript = scriptGenerator.generate('test', 'Empty', actions)
      const browserUseScript = browserUseGenerator.generate('test', 'Empty', actions)

      expect(puppeteerScript).toBeTruthy()
      expect(browserUseScript).toBeTruthy()
    })

    it('should handle special characters in all fields', async () => {
      await recorder.start()

      const bridge = exposedFunctions.get('__recordActionBridge')!

      await bridge(JSON.stringify({
        type: 'input',
        selector: { primary: 'input', fallbacks: [] },
        value: 'Test "quotes" and \'apostrophes\' and \\ backslashes',
      }))

      const actions = await recorder.stop()

      const puppeteerScript = scriptGenerator.generate(
        'special-profile',
        'Handle "special" characters',
        actions
      )

      // Should handle special characters - just verify the script was generated
      expect(puppeteerScript).toBeTruthy()
      expect(puppeteerScript).toContain('await element.type(')
      expect(puppeteerScript).toContain('Test')

      const browserUseScript = browserUseGenerator.generate(
        'special-profile',
        'Handle "special" characters',
        actions
      )

      expect(browserUseScript).toBeTruthy()
      expect(browserUseScript).toContain('await controller.input_text(')
    })

    it('should handle very long action sequences', async () => {
      await recorder.start()

      const bridge = exposedFunctions.get('__recordActionBridge')!

      // Simulate 50 actions
      for (let i = 0; i < 50; i++) {
        await bridge(JSON.stringify({
          type: 'click',
          selector: { primary: `button-${i}`, fallbacks: [] },
        }))
      }

      const actions = await recorder.stop()

      expect(actions.length).toBe(51) // +1 for initial navigate

      const puppeteerScript = scriptGenerator.generate('long-profile', 'Long test', actions)
      const browserUseScript = browserUseGenerator.generate('long-profile', 'Long test', actions)

      expect(puppeteerScript).toBeTruthy()
      expect(browserUseScript).toBeTruthy()

      // Verify all actions are included
      const puppeteerSteps = (puppeteerScript.match(/\/\/ Step \d+:/g) || []).length
      const pythonSteps = (browserUseScript.match(/# Step \d+:/g) || []).length

      expect(puppeteerSteps).toBe(51)
      expect(pythonSteps).toBe(51)
    })
  })

  describe('Options handling', () => {
    it('should respect includeComments option', async () => {
      await recorder.start()

      const bridge = exposedFunctions.get('__recordActionBridge')!
      await bridge(JSON.stringify({
        type: 'click',
        selector: { primary: 'button', fallbacks: [] },
      }))

      const actions = await recorder.stop()

      // With comments
      const withComments = new ScriptGenerator({ includeComments: true })
      const scriptWithComments = withComments.generate('test', 'Test', actions)
      expect(scriptWithComments).toContain('// Step')

      // Without comments
      const withoutComments = new ScriptGenerator({ includeComments: false })
      const scriptWithoutComments = withoutComments.generate('test', 'Test', actions)
      expect(scriptWithoutComments).not.toContain('// Step')
    })

    it('should respect addDelays option', async () => {
      await recorder.start()

      const bridge = exposedFunctions.get('__recordActionBridge')!
      await bridge(JSON.stringify({
        type: 'click',
        selector: { primary: 'button', fallbacks: [] },
      }))

      const actions = await recorder.stop()

      // With delays
      const withDelays = new ScriptGenerator({ addDelays: true })
      const scriptWithDelays = withDelays.generate('test', 'Test', actions)
      expect(scriptWithDelays).toContain('await delay(')

      // Without delays (fewer delay calls)
      const withoutDelays = new ScriptGenerator({ addDelays: false })
      const scriptWithoutDelays = withoutDelays.generate('test', 'Test', actions)

      const delaysWithOption = (scriptWithDelays.match(/await delay\(/g) || []).length
      const delaysWithoutOption = (scriptWithoutDelays.match(/await delay\(/g) || []).length

      expect(delaysWithOption).toBeGreaterThan(delaysWithoutOption)
    })
  })
})
