import { PlaywrightGenerator } from '../lib/PlaywrightGenerator'
import { RecordedAction } from '../types'

describe('PlaywrightGenerator E2E Tests', () => {
  let generator: PlaywrightGenerator

  const makeAction = (overrides: Partial<RecordedAction>): RecordedAction => ({
    type: 'click',
    timestamp: Date.now(),
    selector: { primary: 'button', fallbacks: [] },
    page: { url: 'https://example.com', title: 'Example' },
    ...overrides,
  })

  beforeEach(() => {
    generator = new PlaywrightGenerator({ includeComments: true, addDelays: true })
  })

  describe('Header generation', () => {
    it('should include Playwright imports', () => {
      const script = generator.generate('test', 'Test Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain("from playwright.sync_api import")
    })

    it('should include AUTO-GENERATED comment', () => {
      const script = generator.generate('test', 'Test Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('AUTO-GENERATED by browser-use-codegen')
    })

    it('should include task/prompt in header', () => {
      const script = generator.generate('test', 'Scrape product prices', [makeAction({ type: 'navigate' })])
      expect(script).toContain('Scrape product prices')
    })

    it('should include profile ID in header', () => {
      const script = generator.generate('my-profile-001', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('my-profile-001')
    })

    it('should include action count in header', () => {
      const actions = [makeAction({ type: 'navigate' }), makeAction({ type: 'click' })]
      const script = generator.generate('test', 'Task', actions)
      expect(script).toContain('Actions: 2')
    })
  })

  describe('Playwright structure', () => {
    it('should generate with_playwright context manager', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('with sync_playwright() as p')
    })

    it('should launch chromium browser', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('p.chromium.launch')
    })

    it('should create a new page', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('browser.new_page()')
    })

    it('should have main function', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toMatch(/^def run\(\)/m)
    })

    it('should have __main__ guard', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('if __name__ == "__main__":')
    })

    it('should close browser in finally block', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('browser.close()')
    })
  })

  describe('Navigate action', () => {
    it('should generate page.goto for navigate actions', () => {
      const action = makeAction({ type: 'navigate', page: { url: 'https://example.com/page', title: 'Test' } })
      const script = generator.generate('test', 'Task', [action])
      expect(script).toContain("page.goto('https://example.com/page'")
    })

    it('should include wait_until parameter', () => {
      const action = makeAction({ type: 'navigate', page: { url: 'https://example.com', title: 'Test' } })
      const script = generator.generate('test', 'Task', [action])
      expect(script).toContain("wait_until='networkidle'")
    })
  })

  describe('Click action', () => {
    it('should generate page.locator().click() for click actions', () => {
      const action = makeAction({ type: 'click', selector: { primary: '[data-testid="btn"]', fallbacks: [] } })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('page.locator')
      expect(script).toContain('.click()')
    })

    it('should include fallback selectors', () => {
      const action = makeAction({
        type: 'click',
        selector: { primary: '[data-testid="btn"]', fallbacks: ['#submit', 'button.submit'] }
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('data-testid')
    })

    it('should add wait before click when delays enabled', () => {
      const action = makeAction({ type: 'click', selector: { primary: 'button', fallbacks: [] } })
      const withDelays = new PlaywrightGenerator({ addDelays: true })
      const script = withDelays.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('page.wait_for_timeout')
    })
  })

  describe('Input action', () => {
    it('should generate fill for input actions', () => {
      const action = makeAction({
        type: 'input',
        selector: { primary: '#name-input', fallbacks: [] },
        value: 'John Doe',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('.fill(')
      expect(script).toContain('John Doe')
    })

    it('should handle Enter key with press()', () => {
      const action = makeAction({
        type: 'input',
        selector: { primary: 'input', fallbacks: [] },
        value: 'search term[Enter]',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain(".press('Enter')")
    })

    it('should clear field before typing', () => {
      const action = makeAction({
        type: 'input',
        selector: { primary: 'input', fallbacks: [] },
        value: 'some text',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('.clear()')
    })
  })

  describe('Select action', () => {
    it('should generate select_option for select actions', () => {
      const action = makeAction({
        type: 'select',
        selector: { primary: '#country', fallbacks: [] },
        value: 'US',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('select_option(')
      expect(script).toContain('US')
    })
  })

  describe('Scroll action', () => {
    it('should generate evaluate with scrollTo for body scroll', () => {
      const action = makeAction({
        type: 'scroll',
        selector: { primary: 'body', fallbacks: [] },
        value: '800',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('page.evaluate')
      expect(script).toContain('scrollTo')
    })
  })

  describe('Wait action', () => {
    it('should generate page.wait_for_timeout for wait actions', () => {
      const action = makeAction({ type: 'wait', value: '2000' })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('page.wait_for_timeout(2000)')
    })

    it('should default to 1000ms when no value', () => {
      const action = makeAction({ type: 'wait' })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('page.wait_for_timeout(1000)')
    })
  })

  describe('Extract action', () => {
    it('should generate locator text_content for extract actions', () => {
      const action = makeAction({
        type: 'extract',
        selector: { primary: 'h1.title', fallbacks: [] },
        value: 'productTitle',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('productTitle')
      expect(script).toContain('text_content()')
    })

    it('should assign extracted value to variable', () => {
      const action = makeAction({
        type: 'extract',
        selector: { primary: '.price', fallbacks: [] },
        value: 'productPrice',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('productPrice =')
    })
  })

  describe('Step comments', () => {
    it('should include step comments when enabled', () => {
      const action = makeAction({ type: 'click', selector: { primary: 'button', fallbacks: [] } })
      const withComments = new PlaywrightGenerator({ includeComments: true })
      const script = withComments.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('# Step')
    })

    it('should omit step comments when disabled', () => {
      const action = makeAction({ type: 'click', selector: { primary: 'button', fallbacks: [] } })
      const withoutComments = new PlaywrightGenerator({ includeComments: false })
      const script = withoutComments.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).not.toContain('# Step')
    })
  })

  describe('Python syntax', () => {
    it('should use 4-space indentation', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      const lines = script.split('\n').filter((l: string) => l.startsWith('    '))
      expect(lines.length).toBeGreaterThan(0)
    })

    it('should have balanced indentation (no syntax errors)', () => {
      const actions = [
        makeAction({ type: 'navigate', page: { url: 'https://example.com', title: 'Example' } }),
        makeAction({ type: 'click', selector: { primary: 'button', fallbacks: [] } }),
        makeAction({ type: 'input', selector: { primary: 'input', fallbacks: [] }, value: 'hello' }),
        makeAction({ type: 'extract', selector: { primary: 'h1', fallbacks: [] }, value: 'title' }),
      ]
      const script = generator.generate('test', 'Task', actions)

      // No hanging colons without indented block
      const colonLines = script.split('\n').filter((l: string) => l.trim().endsWith(':'))
      expect(colonLines.length).toBeGreaterThan(0) // Should have blocks
    })
  })

  describe('Full workflow', () => {
    it('should generate a complete e-commerce scraper script', () => {
      const actions: RecordedAction[] = [
        makeAction({ type: 'navigate', page: { url: 'https://shop.example.com', title: 'Shop' } }),
        makeAction({ type: 'input', selector: { primary: '#search', fallbacks: ['input[name="q"]'] }, value: 'laptop' }),
        makeAction({ type: 'click', selector: { primary: '[data-testid="search-btn"]', fallbacks: ['button[type="submit"]'] } }),
        makeAction({ type: 'wait', value: '2000' }),
        makeAction({ type: 'extract', selector: { primary: '.product-title', fallbacks: ['h2.title'] }, value: 'productName' }),
        makeAction({ type: 'extract', selector: { primary: '.price', fallbacks: ['.cost'] }, value: 'productPrice' }),
        makeAction({ type: 'scroll', selector: { primary: 'body', fallbacks: [] }, value: '1000' }),
      ]

      const script = generator.generate('shop-profile', 'Scrape laptop prices', actions)

      expect(script).toContain('AUTO-GENERATED by browser-use-codegen')
      expect(script).toContain('shop-profile')
      expect(script).toContain('Scrape laptop prices')
      expect(script).toContain('https://shop.example.com')
      expect(script).toContain('laptop')
      expect(script).toContain('productName')
      expect(script).toContain('productPrice')
      expect(script).toContain('sync_playwright')

      // Count step comments
      const stepMatches = (script.match(/# Step \d+:/g) || []).length
      expect(stepMatches).toBe(actions.length)
    })

    it('should handle empty actions gracefully', () => {
      const script = generator.generate('test', 'Empty task', [])
      expect(script).toBeTruthy()
      expect(script).toContain('def run()')
    })
  })

  describe('Options', () => {
    it('should default to includeComments=true and addDelays=true', () => {
      const defaultGen = new PlaywrightGenerator()
      const script = defaultGen.generate('test', 'Task', [
        makeAction({ type: 'navigate' }),
        makeAction({ type: 'click' }),
      ])
      expect(script).toContain('# Step')
      expect(script).toContain('page.wait_for_timeout')
    })

    it('should respect headless option in launch args', () => {
      const headlessGen = new PlaywrightGenerator({ headless: false })
      const script = headlessGen.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('headless=False')
    })
  })
})
