import { ScriptGenerator } from '../lib/ScriptGenerator'
import { RecordedAction } from '../types'
import * as fs from 'fs'
import * as path from 'path'

describe('ScriptGenerator E2E', () => {
  let generator: ScriptGenerator
  let sampleActions: RecordedAction[]

  beforeEach(() => {
    generator = new ScriptGenerator()

    // Load fixture actions
    const fixturesPath = path.join(__dirname, 'fixtures', 'actions.json')
    sampleActions = JSON.parse(fs.readFileSync(fixturesPath, 'utf-8'))
  })

  describe('generate()', () => {
    it('should generate valid TypeScript script from recorded actions', () => {
      const script = generator.generate('test-profile', 'Test automation', sampleActions)

      expect(script).toContain('AUTO-GENERATED by browser-use-codegen')
      expect(script).toContain('Test automation')
      expect(script).toContain('test-profile')
      expect(script).toContain('import { Page, ElementHandle, Browser } from \'puppeteer-core\'')
      expect(script).toContain('export async function execute(page: Page)')
    })

    it('should include comments when enabled', () => {
      const generatorWithComments = new ScriptGenerator({ includeComments: true })
      const script = generatorWithComments.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('// Step')
      expect(script).toContain('// Step 1:')
    })

    it('should exclude comments when disabled', () => {
      const generatorNoComments = new ScriptGenerator({ includeComments: false })
      const script = generatorNoComments.generate('test-profile', 'Test', sampleActions)

      // Should not have step comments
      expect(script).not.toContain('// Step 1:')

      // But should still have helper comments
      expect(script).toContain('// Helper for delays')
    })

    it('should include delays when enabled', () => {
      const generatorWithDelays = new ScriptGenerator({ addDelays: true })
      const script = generatorWithDelays.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('await delay(')
    })

    it('should handle empty actions array', () => {
      const script = generator.generate('test-profile', 'Test', [])

      expect(script).toContain('No actions recorded')
      expect(script).toContain('export async function execute(page: Page)')
    })
  })

  describe('action type generation', () => {
    it('should generate navigate action code', () => {
      const navigateAction: RecordedAction = {
        type: 'navigate',
        timestamp: Date.now(),
        selector: { primary: 'body', fallbacks: [] },
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Navigate test', [navigateAction])

      expect(script).toContain('await page.goto(\'https://example.com\'')
      expect(script).toContain('networkidle2')
    })

    it('should generate click action code with selector fallbacks', () => {
      const clickAction: RecordedAction = {
        type: 'click',
        timestamp: Date.now(),
        selector: {
          primary: '[data-testid="button"]',
          fallbacks: ['#submit', 'button.primary'],
        },
        target: { tagName: 'button', text: 'Click me' },
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Click test', [clickAction])

      expect(script).toContain('[data-testid="button"]')
      expect(script).toContain('#submit')
      expect(script).toContain('button.primary')
      expect(script).toContain('await element.click()')
    })

    it('should generate input action code', () => {
      const inputAction: RecordedAction = {
        type: 'input',
        timestamp: Date.now(),
        selector: { primary: '#email', fallbacks: [] },
        value: 'test@example.com',
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Input test', [inputAction])

      expect(script).toContain('#email')
      expect(script).toContain('test@example.com')
      expect(script).toContain('await element.type(')
    })

    it('should generate input action with Enter key', () => {
      const inputAction: RecordedAction = {
        type: 'input',
        timestamp: Date.now(),
        selector: { primary: '#search', fallbacks: [] },
        value: 'search term[Enter]',
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Input enter test', [inputAction])

      expect(script).toContain('search term')
      // [Enter] should not appear in the type() call, only in comments
      expect(script).toContain('await element.type(\'search term\'')
      expect(script).toContain('await element.press(\'Enter\')')
    })

    it('should generate select action code', () => {
      const selectAction: RecordedAction = {
        type: 'select',
        timestamp: Date.now(),
        selector: { primary: '#country', fallbacks: [] },
        value: 'US',
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Select test', [selectAction])

      expect(script).toContain('#country')
      expect(script).toContain('await element.select(\'US\')')
    })

    it('should generate scroll action code for window', () => {
      const scrollAction: RecordedAction = {
        type: 'scroll',
        timestamp: Date.now(),
        selector: { primary: 'body', fallbacks: [] },
        value: '500',
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Scroll test', [scrollAction])

      expect(script).toContain('window.scrollTo(0, 500)')
    })

    it('should generate scroll action code for element', () => {
      const scrollAction: RecordedAction = {
        type: 'scroll',
        timestamp: Date.now(),
        selector: { primary: '.container', fallbacks: [] },
        value: '300',
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Scroll test', [scrollAction])

      expect(script).toContain('.container')
      expect(script).toContain('el.scrollTop = 300')
    })

    it('should generate wait action code', () => {
      const waitAction: RecordedAction = {
        type: 'wait',
        timestamp: Date.now(),
        selector: { primary: 'body', fallbacks: [] },
        value: '2000',
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Wait test', [waitAction])

      expect(script).toContain('await delay(2000)')
    })

    it('should generate extract action code with result assignment', () => {
      const extractAction: RecordedAction = {
        type: 'extract',
        timestamp: Date.now(),
        selector: { primary: '.price', fallbacks: ['.amount'] },
        value: 'productPrice',
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Extract test', [extractAction])

      expect(script).toContain('// Extract productPrice')
      expect(script).toContain('productPrice')
      expect(script).toContain('.price')
      expect(script).toContain('result[\'productPrice\']')
    })
  })

  describe('TypeScript interface generation', () => {
    it('should generate interface for extracted fields', () => {
      const actions: RecordedAction[] = [
        {
          type: 'extract',
          timestamp: Date.now(),
          selector: { primary: '.price', fallbacks: [] },
          value: 'price',
          page: { url: 'https://example.com', title: 'Example' },
        },
        {
          type: 'extract',
          timestamp: Date.now(),
          selector: { primary: '.title', fallbacks: [] },
          value: 'title',
          page: { url: 'https://example.com', title: 'Example' },
        },
      ]

      const script = generator.generate('test-profile', 'Extract test', actions)

      expect(script).toContain('interface ScrapeResult')
      expect(script).toContain('price?: string | null')
      expect(script).toContain('title?: string | null')
    })

    it('should use Record type when no extracted fields', () => {
      const actions: RecordedAction[] = [
        {
          type: 'click',
          timestamp: Date.now(),
          selector: { primary: 'button', fallbacks: [] },
          page: { url: 'https://example.com', title: 'Example' },
        },
      ]

      const script = generator.generate('test-profile', 'Click test', actions)

      expect(script).toContain('type ScrapeResult = Record<string, any>')
    })
  })

  describe('generated script structure', () => {
    it('should include header with metadata', () => {
      const script = generator.generate('my-profile', 'My task', sampleActions)

      expect(script).toContain('AUTO-GENERATED by browser-use-codegen')
      expect(script).toContain('Task: "My task"')
      expect(script).toContain('Profile: my-profile')
      expect(script).toContain('Actions: ' + sampleActions.length)
      expect(script).toMatch(/Generated: \d{4}-\d{2}-\d{2}/)
    })

    it('should include execute function', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('export async function execute(page: Page): Promise<ScrapeResult>')
      expect(script).toContain('const result: ScrapeResult = {}')
      expect(script).toContain('return result')
    })

    it('should include runWithBrowser helper', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('export async function runWithBrowser(')
      expect(script).toContain('browser: Browser')
      expect(script).toContain('const page = await browser.newPage()')
    })

    it('should include standalone main function', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('export default async function main()')
      expect(script).toContain('PUPPETEER_WS_ENDPOINT')
      expect(script).toContain('puppeteer.connect')
    })

    it('should include delay helper', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      expect(script).toContain('const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))')
    })
  })

  describe('selector fallback logic', () => {
    it('should generate try-catch selector fallback pattern', () => {
      const action: RecordedAction = {
        type: 'click',
        timestamp: Date.now(),
        selector: {
          primary: '[data-testid="btn"]',
          fallbacks: ['#submit', 'button'],
        },
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Test', [action])

      expect(script).toContain('const selectors = [')
      expect(script).toContain('[data-testid="btn"]')
      expect(script).toContain('#submit')
      expect(script).toContain('for (const selector of selectors)')
      expect(script).toContain('await page.waitForSelector(selector, { timeout: 5000 })')
      expect(script).toContain('// Try next selector')
    })

    it('should generate warning for missing elements', () => {
      const action: RecordedAction = {
        type: 'click',
        timestamp: Date.now(),
        selector: { primary: 'button', fallbacks: [] },
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Test', [action])

      expect(script).toContain('console.warn(\'Element not found for action: click\')')
      expect(script).toContain('// Skip this action and continue')
    })
  })

  describe('special character handling', () => {
    it('should escape quotes in selectors', () => {
      const action: RecordedAction = {
        type: 'click',
        timestamp: Date.now(),
        selector: { primary: 'button[data-value="it\'s"]', fallbacks: [] },
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Test', [action])

      expect(script).toContain('button[data-value="it\\\'s"]')
    })

    it('should escape quotes in input values', () => {
      const action: RecordedAction = {
        type: 'input',
        timestamp: Date.now(),
        selector: { primary: 'input', fallbacks: [] },
        value: 'He said "hello"',
        page: { url: 'https://example.com', title: 'Example' },
      }

      const script = generator.generate('test-profile', 'Test', [action])

      // The generated script contains: await element.type('He said "hello"')
      // In the source code string, quotes inside single-quoted strings don't need escaping
      expect(script).toContain('He said "hello"')
    })

    it('should escape quotes in task description', () => {
      const script = generator.generate('test-profile', 'Test "automation" task', sampleActions)

      expect(script).toContain('Task: "Test \\"automation\\" task"')
    })
  })

  describe('multiple actions integration', () => {
    it('should generate complete script with all action types', () => {
      const script = generator.generate('test-profile', 'Complete test', sampleActions)

      // Check all action types are present
      expect(script).toContain('await page.goto(') // navigate
      expect(script).toContain('await element.click()') // click
      expect(script).toContain('await element.type(') // input
      expect(script).toContain('await element.select(') // select
      expect(script).toContain('window.scrollTo') // scroll
      expect(script).toContain('await delay(') // wait
      expect(script).toContain('// Extract productPrice') // extract
    })

    it('should maintain action order', () => {
      const script = generator.generate('test-profile', 'Test', sampleActions)

      // Extract step comments to verify order
      const stepComments = script.match(/\/\/ Step \d+:/g) || []

      expect(stepComments.length).toBe(sampleActions.length)
      expect(stepComments[0]).toBe('// Step 1:')
      expect(stepComments[stepComments.length - 1]).toBe(`// Step ${sampleActions.length}:`)
    })
  })

  describe('syntax validation', () => {
    it('should generate syntactically valid TypeScript', () => {
      const script = generator.generate('test-profile', 'Syntax test', sampleActions)

      // Check for balanced braces
      const openBraces = (script.match(/{/g) || []).length
      const closeBraces = (script.match(/}/g) || []).length
      expect(openBraces).toBe(closeBraces)

      // Check for balanced parentheses
      const openParens = (script.match(/\(/g) || []).length
      const closeParens = (script.match(/\)/g) || []).length
      expect(openParens).toBe(closeParens)

      // Check for proper async/await usage
      const asyncFunctions = script.match(/async function/g) || []
      expect(asyncFunctions.length).toBeGreaterThan(0)
    })
  })
})
