import { SeleniumGenerator } from '../lib/SeleniumGenerator'
import { RecordedAction } from '../types'

describe('SeleniumGenerator E2E Tests', () => {
  let generator: SeleniumGenerator

  const makeAction = (overrides: Partial<RecordedAction>): RecordedAction => ({
    type: 'click',
    timestamp: Date.now(),
    selector: { primary: 'button', fallbacks: [] },
    page: { url: 'https://example.com', title: 'Example' },
    ...overrides,
  })

  beforeEach(() => {
    generator = new SeleniumGenerator({ includeComments: true, addDelays: true })
  })

  describe('Header generation', () => {
    it('should include Selenium imports', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('from selenium import webdriver')
      expect(script).toContain('from selenium.webdriver.common.by import By')
    })

    it('should include AUTO-GENERATED comment', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('AUTO-GENERATED by browser-use-codegen')
    })

    it('should include task/prompt in header', () => {
      const script = generator.generate('test', 'Automate login flow', [makeAction({ type: 'navigate' })])
      expect(script).toContain('Automate login flow')
    })

    it('should include profile ID in header', () => {
      const script = generator.generate('login-profile-01', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('login-profile-01')
    })

    it('should include action count in header', () => {
      const actions = [makeAction({ type: 'navigate' }), makeAction({ type: 'click' }), makeAction({ type: 'input' })]
      const script = generator.generate('test', 'Task', actions)
      expect(script).toContain('Actions: 3')
    })
  })

  describe('Selenium structure', () => {
    it('should create Chrome webdriver', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('webdriver.Chrome')
    })

    it('should have ChromeOptions setup', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('ChromeOptions')
    })

    it('should quit driver in finally block', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('driver.quit()')
    })

    it('should have main run function', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toMatch(/^def run\(\)/m)
    })

    it('should have __main__ guard', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('if __name__ == "__main__":')
    })
  })

  describe('Navigate action', () => {
    it('should generate driver.get for navigate actions', () => {
      const action = makeAction({ type: 'navigate', page: { url: 'https://shop.example.com', title: 'Shop' } })
      const script = generator.generate('test', 'Task', [action])
      expect(script).toContain("driver.get('https://shop.example.com')")
    })
  })

  describe('Click action', () => {
    it('should generate find_element + click for click actions', () => {
      const action = makeAction({ type: 'click', selector: { primary: '[data-testid="btn"]', fallbacks: [] } })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('find_element')
      expect(script).toContain('.click()')
    })

    it('should use CSS_SELECTOR for data-testid selectors', () => {
      const action = makeAction({ type: 'click', selector: { primary: '[data-testid="submit"]', fallbacks: [] } })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('By.CSS_SELECTOR')
    })

    it('should use By.ID for ID selectors', () => {
      const action = makeAction({ type: 'click', selector: { primary: '#submit-btn', fallbacks: [] } })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('By.ID')
    })

    it('should use By.XPATH or CSS_SELECTOR for other selectors', () => {
      const action = makeAction({ type: 'click', selector: { primary: 'div.container > button', fallbacks: [] } })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toMatch(/By\.(CSS_SELECTOR|XPATH)/)
    })

    it('should add time.sleep after click when delays enabled', () => {
      const action = makeAction({ type: 'click', selector: { primary: 'button', fallbacks: [] } })
      const withDelays = new SeleniumGenerator({ addDelays: true })
      const script = withDelays.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('time.sleep')
    })

    it('should include fallback selectors with try/except', () => {
      const action = makeAction({
        type: 'click',
        selector: { primary: '[data-testid="btn"]', fallbacks: ['#submit', 'button.submit'] }
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('except')
    })
  })

  describe('Input action', () => {
    it('should generate send_keys for input actions', () => {
      const action = makeAction({
        type: 'input',
        selector: { primary: '#email', fallbacks: [] },
        value: 'user@example.com',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('send_keys')
      expect(script).toContain('user@example.com')
    })

    it('should clear field before sending keys', () => {
      const action = makeAction({
        type: 'input',
        selector: { primary: 'input', fallbacks: [] },
        value: 'hello',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('.clear()')
    })

    it('should handle Enter key with Keys.RETURN', () => {
      const action = makeAction({
        type: 'input',
        selector: { primary: 'input', fallbacks: [] },
        value: 'search[Enter]',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('Keys.RETURN')
      expect(script).toContain('from selenium.webdriver.common.keys import Keys')
    })
  })

  describe('Select action', () => {
    it('should use Select class for select actions', () => {
      const action = makeAction({
        type: 'select',
        selector: { primary: '#country', fallbacks: [] },
        value: 'US',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('Select(')
      expect(script).toContain('select_by_value')
      expect(script).toContain('from selenium.webdriver.support.ui import Select')
    })
  })

  describe('Scroll action', () => {
    it('should use execute_script for scroll actions', () => {
      const action = makeAction({
        type: 'scroll',
        selector: { primary: 'body', fallbacks: [] },
        value: '800',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('execute_script')
      expect(script).toContain('scrollTo')
    })
  })

  describe('Wait action', () => {
    it('should generate time.sleep for wait actions', () => {
      const action = makeAction({ type: 'wait', value: '3000' })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('time.sleep(3)')
    })

    it('should convert milliseconds to seconds', () => {
      const action = makeAction({ type: 'wait', value: '1500' })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('time.sleep(1.5)')
    })

    it('should default to 1 second when no value', () => {
      const action = makeAction({ type: 'wait' })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('time.sleep(1)')
    })
  })

  describe('Extract action', () => {
    it('should generate find_element + text for extract actions', () => {
      const action = makeAction({
        type: 'extract',
        selector: { primary: '.product-name', fallbacks: [] },
        value: 'productName',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('productName')
      expect(script).toContain('.text')
    })

    it('should assign extracted value to result dict', () => {
      const action = makeAction({
        type: 'extract',
        selector: { primary: '.price', fallbacks: [] },
        value: 'price',
      })
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain("result['price']")
    })
  })

  describe('Step comments', () => {
    it('should include step comments when enabled', () => {
      const action = makeAction({ type: 'click' })
      const withComments = new SeleniumGenerator({ includeComments: true })
      const script = withComments.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).toContain('# Step')
    })

    it('should omit step comments when disabled', () => {
      const action = makeAction({ type: 'click' })
      const withoutComments = new SeleniumGenerator({ includeComments: false })
      const script = withoutComments.generate('test', 'Task', [makeAction({ type: 'navigate' }), action])
      expect(script).not.toContain('# Step')
    })
  })

  describe('Import completeness', () => {
    it('should import time module', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('import time')
    })

    it('should import WebDriverWait for explicit waits', () => {
      const script = generator.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('WebDriverWait')
    })
  })

  describe('Full workflow', () => {
    it('should generate a complete login automation script', () => {
      const actions: RecordedAction[] = [
        makeAction({ type: 'navigate', page: { url: 'https://app.example.com/login', title: 'Login' } }),
        makeAction({ type: 'input', selector: { primary: '#username', fallbacks: ['input[name="user"]'] }, value: 'admin' }),
        makeAction({ type: 'input', selector: { primary: '#password', fallbacks: ['input[type="password"]'] }, value: 'secret[Enter]' }),
        makeAction({ type: 'wait', value: '2000' }),
        makeAction({ type: 'extract', selector: { primary: '.welcome-msg', fallbacks: [] }, value: 'welcomeMessage' }),
      ]

      const script = generator.generate('auth-profile', 'Login and verify welcome message', actions)

      expect(script).toContain('AUTO-GENERATED by browser-use-codegen')
      expect(script).toContain('auth-profile')
      expect(script).toContain('Login and verify welcome message')
      expect(script).toContain('https://app.example.com/login')
      expect(script).toContain('admin')
      expect(script).toContain('Keys.RETURN')
      expect(script).toContain('time.sleep(2)')
      expect(script).toContain('welcomeMessage')
      expect(script).toContain('from selenium import webdriver')

      const stepMatches = (script.match(/# Step \d+:/g) || []).length
      expect(stepMatches).toBe(actions.length)
    })

    it('should handle empty actions gracefully', () => {
      const script = generator.generate('test', 'Empty task', [])
      expect(script).toBeTruthy()
      expect(script).toContain('def run()')
    })
  })

  describe('Options', () => {
    it('should default to includeComments=true and addDelays=true', () => {
      const defaultGen = new SeleniumGenerator()
      const script = defaultGen.generate('test', 'Task', [
        makeAction({ type: 'navigate' }),
        makeAction({ type: 'click' }),
      ])
      expect(script).toContain('# Step')
      expect(script).toContain('time.sleep')
    })

    it('should respect headless option in Chrome options', () => {
      const headlessGen = new SeleniumGenerator({ headless: true })
      const script = headlessGen.generate('test', 'Task', [makeAction({ type: 'navigate' })])
      expect(script).toContain('headless')
    })
  })
})
